In [17]:
import tensorflow as tf

In [18]:
x =  tf.constant([[[1,2],[3,4]],
                 [[5,6],[7,8]]])

In [19]:
with tf.Session():
    print(x.shape)
    print(x.eval())

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
y = tf.expand_dims(x,1)
with tf.Session():
    print(y.shape)
    print(y.eval())

(2, 1, 2, 2)
[[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]]


In [21]:
z = tf.expand_dims(x,0)
with tf.Session():
    print(z.shape)

(1, 2, 2, 2)
