In [12]:
import numpy as np

In [13]:
a = np.array([[1.0,2.0],
              [3.0,4.0]])

In [14]:
print(a.shape)
print(a)

(2, 2)
[[1. 2.]
 [3. 4.]]


In [15]:
b = np.zeros((2,2,1))
b[:,:,0]=a

In [16]:
print(b.shape)
print(b)

(2, 2, 1)
[[[1.]
  [2.]]

 [[3.]
  [4.]]]


In [17]:
c = np.squeeze(b)

In [18]:
print(c.shape)
print(c)

(2, 2)
[[1. 2.]
 [3. 4.]]


In [19]:
Z_train2 = np.zeros((m_train, n_H * n_W, 1))  # 从数组的形状中删除单维度条目，即把shape中为1的维度去掉
Z_train2[:, :, 0] = np.squeeze(temp_Z_train)
# todo 此处为何不直接 Z_train2_out=temp_Z_train
Z_train2_out = np.squeeze(Z_train2[:, :, 0])

(2, 2)
[[1. 2.]
 [3. 4.]]
