In [2]:
import tensorflow as tf

In [12]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])

In [13]:
y = tf.transpose(x)  
with tf.Session():
    print(y.eval())

[[1 4]
 [2 5]
 [3 6]]


In [14]:
y = tf.transpose(x, perm=[1, 0])
with tf.Session():
    print(y.eval())

[[1 4]
 [2 5]
 [3 6]]


#### If x is complex, setting conjugate=True gives the conjugate transpose

In [16]:
x = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])

In [17]:
y = tf.transpose(x, conjugate=True) 
with tf.Session():
    print(y.eval())

[[1.-1.j 4.-4.j]
 [2.-2.j 5.-5.j]
 [3.-3.j 6.-6.j]]


#### 'perm' is more useful for n-dimensional tensors, for n > 2

In [22]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])
print(x.shape)

(2, 2, 3)


#### Take the transpose of the matrices in dimension-0 (this common operation has a shorthand `matrix_transpose`)

In [21]:
y = tf.transpose(x, perm=[0, 2, 1])
with tf.Session():
    print(y.eval())
    print(y.shape)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]
(2, 3, 2)
